# Default initial positions for arm_description's ros2_control fake system

initial_positions:
  shoulder_pitch_joint: 0.0
  shoulder_roll_joint: 0.0
  shoulder_yaw_joint: 0.0
  elbow_pitch_joint: 0.0
  elbow_yaw_joint: 0.0
