arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  default_acceleration_scaling_factor: 1.0
  default_velocity_scaling_factor: 1.0
  position_only_ik: true
  # Alternative: Use TRAC-IK for better performance (install: sudo apt install ros-${ROS_DISTRO}-trac-ik-kinematics-plugin)
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin