# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_roll_joint
    action_ns: follow_joint_trajectory
    default: true

  hand_controller:
    type: FollowJointTrajectory
    joints:
      - left_palm_right_finger
      - left_palm_left_finger
    action_ns: follow_joint_trajectory
    default: true
