controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    servo_controller:
      type: forward_command_controller/ForwardCommandController


arm_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

servo_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_roll_joint
    interface_name: position
