controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - base_rotation_joint
        - shoulder_pitch_joint
        - elbow_pitch_joint
        - wrist_pitch_joint
        - wrist_roll_joint
      gains:
        base_rotation_joint: {p: 100.0, d: 1.0}
        shoulder_pitch_joint: {p: 100.0, d: 1.0}
        elbow_pitch_joint: {p: 100.0, d: 1.0}
        wrist_pitch_joint: {p: 50.0, d: 0.5}
        wrist_roll_joint: {p: 50.0, d: 0.5}